git commit -m "Refactor Gait application for enhanced output and error handling

- Added ConsoleOutput service for structured console messaging
- Updated App class to use ConsoleOutput for user feedback
- Changed ApiKey to ApiKeyVar in OpenAI configuration
- Enhanced GitDiffService to handle errors using Result type
- Improved error messaging in AIService for API key retrieval
- Introduced appsettings.Production.json for production configuration 
- Restructured Program.cs to support modular logging configuration 
- Created Result struct for improved handling of success and error cases in services
- Added support for retrieving diff commands with staged changes

 ** Generated by Gait **"
